[package]
name = "ttcp"
version = "0.1.0"
authors = ["sidharthk <sidharth.k9@mailbox.org>"]
edition = "2018"

[dependencies]
tun-tap = "0.1.2"
etherparse = "0.8"
bitflags = "1.0"
nix = "0.13"

[lib]
name = "ttcp"

[[bin]]
name = "ttcp"